### ISSUE TITLE
Request: Allow config option to make packs be able to be turned off

### ISSUE THREAD

**Issue by Vazkii** [Darkhax-Minecraft/Open-Loader#8]
My modpack ships with 2 built-in non-essential, resource packs. It would be great if they could be turned off in the menu while still enabled by default.

**Comment by Darkhax** [comment]
I implemented this using the `pack.mcmeta` file. You can also change load priority but you probably don't need it.

| Value     | Desc                                     | Default | Valid Options |
|-----------|------------------------------------------|---------|---------------|
| builtin   | Whether or not the pack is non-disableable. | true    | true / false  |
| priority  | The load priority of the pack.           | top     | top / bottom  |

**example**
```json
{
    "pack": {
        "pack_format": 6,
        "description": "Test Resource Pack"
    },
    "openloader": {
        "builtin": false
    }
}
```

https://www.curseforge.com/minecraft/mc-mods/open-loader/files/3198395

**Comment by Vazkii** [comment]
This doesn't fully fix the issue. Setting "builtin" to false also makes the pack be disabled by default.

**Comment by Darkhax** [comment]
@Vazkii The vanilla resource pack system really isn't designed to handle that use case as the "allow disabling" and "enabled by default" mechanics are tied together. I've released a new beta which uses a few mixins to try and get this working though. There is now a `defaultEnabled` property which defaults to true. 

Let me know if you encounter any issues or have any ideas on how to improve the implementation.
